spring:
  proffiles:
    active:
      - prod

  datasource:
    url: jdbc:postgresql://localhost:15432/casadocodigodb
    username: postgres
    password: postgres
  #    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false

#spring:
#  profiles: prod
#
#  datasource:
#    url: ${JDBC_DATABASE_URL}
#    username: ${JDBC_DATABASE_USERNAME}
#    password: ${JDBC_DATABASE_PASSWORD}
##    hikari:
##      auto-commit: false
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        format_sql: true
##        jdbc.lob.non_contextual_creation: true
##        connection:
##          provider_disables_autocommit: true
#
##    open-in-view: false
#
#  data:
#    rest:
#      base-path: /api
